define((require, exports, module) => {
  return {
	'3': {'3': 'Mikazuki', 'full': 'Mikazuki Munechika'},
	'4': {'4': 'Mikazuki', 'full': 'Mikazuki Munechika'},
	'5': {'5': 'Kogitsunemaru', 'full': 'Kogitsunemaru'},
	'6': {'6': 'Kogitsunemaru', 'full': 'Kogitsunemaru'},
	'7': {'7': 'Ishikirimaru', 'full': 'Ishikirimaru'},
	'8': {'8': 'Ishikirimaru', 'full': 'Ishikirimaru'},
	'9': {'9': 'Iwatooshi', 'full': 'Iwatooshi'},
	'10': {'10': 'Iwatooshi', 'full': 'Iwatooshi'},
	'11': {'11': 'Imanotsurugi', 'full': 'Imanotsurugi'},
	'12': {'12': 'Imanotsurugi', 'full': 'Imanotsurugi'},
	'13': {'13': 'Oodenta', 'full': 'Oodenta Mitsuyo'},
	'14': {'14': 'Oodenta', 'full': 'Oodenta Mitsuyo'},
	'15': {'15': 'Sohayanotsurugi', 'full': 'Sohayanotsurugi'},
	'16': {'16': 'Sohayanotsurugi', 'full': 'Sohayanotsurugi'},
	'17': {'17': 'Juzumaru', 'full': 'Juzumaru Tsunetsugu'},
	'18': {'18': 'Juzumaru', 'full': 'Juzumaru Tsunetsugu'},
	'19': {'19': 'Nikkari', 'full': 'Nikkari Aoe'},
	'20': {'20': 'Nikkari', 'full': 'Nikkari Aoe'},
	'21': {'21':'Onimaru', 'full': 'Onimaru Kunitsuna'},
	'22': {'22':'Onimaru', 'full': 'Onimaru Kunitsuna'},
	'23': {'23': 'Nakigitsune', 'full': 'Nakigitsune'},
	'24': {'24': 'Nakigitsune', 'full': 'Nakigitsune'},
	'25': {'25': 'Ichigo', 'full': 'Ichigo Hitofuri'},
	'26': {'26': 'Ichigo', 'full': 'Ichigo Hitofuri'},
	'27': {'27': 'Namazuo', 'full': 'Namazuo Toushirou'},
	'28': {'28': 'Namazuo', 'full': 'Namazuo Toushirou'},
	'29': {'29': 'Honebami', 'full': 'Honebami Toushirou'},
	'30': {'30': 'Honebami', 'full': 'Honebami Toushirou'},
	'31': {'31': 'Hirano', 'full': 'Hirano Toushirou'},
	'32': {'32': 'Hirano', 'full': 'Hirano Toushirou'},
	'33': {'33': 'Atsushi', 'full': 'Atsushi Toushirou'},
	'34': {'34': 'Atsushi', 'full': 'Atsushi Toushirou'},
	'35': {'35': 'Gotou', 'full': 'Gotou Toushirou'},
	'36': {'36': 'Gotou', 'full': 'Gotou Toushirou'},
	'37': {'37': 'Shinano', 'full': 'Shinano Toushirou'},
	'38': {'38': 'Shinano', 'full': 'Shinano Toushirou'},
	'39': {'39': 'Maeda', 'full': 'Maeda Toushirou'},
	'40': {'40': 'Maeda', 'full': 'Maeda Toushirou'},
	'41': {'41': 'Akita', 'full': 'Akita Toushirou'},
	'42': {'42': 'Akita', 'full': 'Akita Toushirou'},
	'43': {'43': 'Hakata', 'full': 'Hakata Toushirou'},
	'44': {'44': 'Hakata', 'full': 'Hakata Toushirou'},
	'45': {'45': 'Midare', 'full': 'Midare Toushirou'},
	'46': {'46': 'Midare', 'full': 'Midare Toushirou'},
	'47': {'47': 'Gokotai', 'full': 'Gokotai'},
	'48': {'48': 'Gokotai', 'full': 'Gokotai'},
	'49': {'49': 'Yagen', 'full': 'Yagen Toushirou'},
	'50': {'50': 'Yagen', 'full': 'Yagen Toushirou'},
	'51': {'51': 'Houchou', 'full': 'Houchou Toushirou'},
	'52': {'52': 'Houchou', 'full': 'Houchou Toushirou'},
	'53': {'53': 'Ookanehira', 'full': 'Ookanehira'},
	'54': {'54': 'Ookanehira', 'full': 'Ookanehira'},
	'55': {'55': 'Uguisumaru', 'full': 'Uguisumaru'},
	'56': {'56': 'Uguisumaru', 'full': 'Uguisumaru'},
	'57': {'57': 'Akashi', 'full': 'Akashi Kuniyuki'},
	'58': {'58': 'Akashi', 'full': 'Akashi Kuniyuki'},
	'59': {'59': 'Hotarumaru', 'full': 'Hotarumaru'},
	'60': {'60': 'Hotarumaru', 'full': 'Hotarumaru'},
	'61': {'61': 'Aizen', 'full': 'Aizen Kunitoshi'},
	'62': {'62': 'Aizen', 'full': 'Aizen Kunitoshi'},
	'63': {'63': 'Sengo', 'full': 'Sengo Muramasa'},
	'64': {'64': 'Sengo', 'full': 'Sengo Muramasa'},
	'65': {'65': 'Tonbokiri', 'full': 'Tonbokiri'},
	'66': {'66': 'Tonbokiri', 'full': 'Tonbokiri'},
	'67': {'67': 'Monoyoshi', 'full': 'Monoyoshi Sadamune'},
	'68': {'68': 'Monoyoshi', 'full': 'Monoyoshi Sadamune'},
	'69': {'69': 'Taikogane', 'full': 'Taikogane Sadamune'},
	'70': {'70': 'Taikogane', 'full': 'Taikogane Sadamune'},
	'71': {'71': 'Kikkou', 'full': 'Kikkou Sadamune'},
	'72': {'72': 'Kikkou', 'full': 'Kikkou Sadamune'},
	'73': {'73': 'Shokudaikiri', 'full': 'Shokudaikiri Mitsutada'},
	'74': {'74': 'Shokudaikiri', 'full': 'Shokudaikiri Mitsutada'},
	'75': {'75': 'Daihannya', 'full': 'Daihannya Nagamitsu'},
	'76': {'76': 'Daihannya', 'full': 'Daihannya Nagamitsu'},
	'77': {'77': 'Koryuu', 'full': 'Koryuu Kagemitsu'},
	'78': {'78': 'Koryuu', 'full': 'Koryuu Kagemitsu'},
	'79': {'79': 'Kousetsu', 'full': 'Kousetsu Samonji'},
	'80': {'80': 'Kousetsu', 'full': 'Kousetsu Samonji'},
	'81': {'81': 'Souza', 'full': 'Souza Samonji'},
	'82': {'82': 'Souza', 'full': 'Souza Samonji'},
	'83': {'83': 'Sayo', 'full': 'Sayo Samonji'},
	'84': {'84': 'Sayo', 'full': 'Sayo Samonji'},
	'85': {'85': 'Kashuu', 'full': 'Kashuu Kiyomitsu'},
	'86': {'86': 'Kashuu', 'full': 'Kashuu Kiyomitsu'},
	'87': {'87': 'Yamatonokami', 'full': 'Yamatonokami Yasusada'},
	'88': {'88': 'Yamatonokami', 'full': 'Yamatonokami Yasusada'},
	'89': {'89': 'Kasen', 'full': 'Kasen Kanesada'},
	'90': {'90': 'Kasen', 'full': 'Kasen Kanesada'},
	'91': {'91': 'Izuminokami', 'full': 'Izuminokami Kanesada'},
	'92': {'92': 'Izuminokami', 'full': 'Izuminokami Kanesada'},
	'93': {'93': 'Mutsunokami', 'full': 'Mutsunokami Yoshiyuki'},
	'94': {'94': 'Mutsunokami', 'full': 'Mutsunokami Yoshiyuki'},
	'95': {'95': 'Yamanbagiri', 'full': 'Yamanbagiri Kunihiro'},
	'96': {'96': 'Yamanbagiri', 'full': 'Yamanbagiri Kunihiro'},
	'97': {'97': 'Yamabushi', 'full': 'Yamabushi Kunihiro'},
	'98': {'98': 'Yamabushi', 'full': 'Yamabushi Kunihiro'},
	'99': {'99': 'Horikawa', 'full': 'Horikawa Kunihiro'},
	'100': {'100': 'Horikawa', 'full': 'Horikawa Kunihiro'},
	'101': {'101': 'Hachisuka', 'full': 'Hachisuka Kotetsu'},
	'102': {'102': 'Hachisuka', 'full': 'Hachisuka Kotetsu'},
	'103': {'103': 'Urashima', 'full': 'Urashima Kotetsu'},
	'104': {'104': 'Urashima', 'full': 'Urashima Kotetsu'},
	'105': {'105': 'Nagasone', 'full': 'Nagasone Kotetsu'},
	'106': {'106': 'Nagasone', 'full': 'Nagasone Kotetsu'},
	'107': {'107': 'Higekiri', 'full': 'Higekiri'},
	'108': {'108': 'Higekiri', 'full': 'Higekiri'},
	'109': {'109': 'Higekiri', 'full': 'Higekiri'},
	'110': {'110': 'Higekiri', 'full': 'Higekiri'},
	'111': {'111': 'Higekiri', 'full': 'Higekiri'},
	'112': {'112': 'Hizamaru', 'full': 'Hizamaru'},
	'113': {'113': 'Hizamaru', 'full': 'Hizamaru'},
	'114': {'114': 'Hizamaru', 'full': 'Hizamaru'},
	'115': {'115': 'Hizamaru', 'full': 'Hizamaru'},
	'116': {'116': 'Ookurikara', 'full': 'Ookurikara'},
	'117': {'117': 'Ookurikara', 'full': 'Ookurikara'},
	'118': {'118': 'Hasebe', 'full': 'Heshikiri Hasebe'},
	'119': {'119': 'Hasebe', 'full': 'Heshikiri Hasebe'},
	'120': {'120': 'Fudou', 'full': 'Fudou Yukimitsu'},
	'121': {'121': 'Fudou', 'full': 'Fudou Yukimitsu'},
	'122': {'122': 'Shishiou', 'full': 'Shishiou'},
	'123': {'123': 'Shishiou', 'full': 'Shishiou'},
	'124': {'124': 'Kogarasumaru', 'full': 'Kogarasumaru'},
	'125': {'125': 'Kogarasumaru', 'full': 'Kogarasumaru'},
	'128': {'128': 'Doudanuki', 'full': 'Doudanuki Masakuni'},
	'129': {'129': 'Doudanuki', 'full': 'Doudanuki Masakuni'},
	'130': {'130': 'Tsurumaru', 'full': 'Tsurumaru Kuninaga'},
	'131': {'131': 'Tsurumaru', 'full': 'Tsurumaru Kuninaga'},
	'132': {'132': 'Taroutachi', 'full': 'Taroutachi'},
	'133': {'133': 'Taroutachi', 'full': 'Taroutachi'},
	'134': {'134': 'Jiroutachi', 'full': 'Jiroutachi'},
	'135': {'135': 'Jiroutachi', 'full': 'Jiroutachi'},
	'136': {'136': 'Nihongou', 'full': 'Nihongou'},
	'137': {'137': 'Nihongou', 'full': 'Nihongou'},
	'138': {'138': 'Otegine', 'full': 'Otegine'},
	'139': {'139': 'Otegine', 'full': 'Otegine'},
	'140': {'140': 'Tomoegata', 'full': 'Tomoegata Naginata'},
	'141': {'141': 'Tomoegata', 'full': 'Tomoegata Naginata'},
	'142': {'142': 'Mouri', 'full': 'Mouri Toushirou'},
	'143': {'143': 'Mouri', 'full': 'Mouri Toushirou'},
	'144': {'144': 'Kotegiri', 'full': 'Kotegiri Gou'},
	'145': {'145': 'Kotegiri', 'full': 'Kotegiri Gou'},
	'146': {'146': 'Kenshin', 'full': 'Kenshin Kagemitsu'},
	'147': {'147': 'Kenshin', 'full': 'Kenshin Kagemitsu'},
	'148': {'148': 'Azuki', 'full': 'Azuki Nagamitsu'},
	'149': {'149': 'Azuki', 'full': 'Azuki Nagamitsu'},
	'150': {'150': 'Hyuuga', 'full': 'Hyuuga Masamune'},
	'151': {'151': 'Hyuuga', 'full': 'Hyuuga Masamune'},
	'152': {'152': 'Shizukagata', 'full': 'Shizukagata Naginata'},
	'153': {'153': 'Shizukagata', 'full': 'Shizukagata Naginata'},
	'154': {'154': 'Nansen', 'full': 'Nansen Ichimonji'},
	'155': {'155': 'Nansen', 'full': 'Nansen Ichimonji'},
	'156': {'156': 'Chiyoganemaru', 'full': 'Chiyoganemaru'},
	'157': {'157': 'Chiyoganemaru', 'full': 'Chiyoganemaru'},
	'158': {'158': 'Chougi', 'full': 'Yamanbagiri Chougi'},
	'159': {'159': 'Chougi', 'full': 'Yamanbagiri Chougi'},
	'160': {'160': 'Buzen', 'full': 'Buzen Gou'},
	'161': {'161': 'Buzen', 'full': 'Buzen Gou'},
	'162': {'162': 'Nenekirimaru', 'full': 'Nenekirimaru'},
	'163': {'163': 'Nenekirimaru', 'full': 'Nenekirimaru'},
	'164': {'164': 'Hakusan', 'full': 'Hakusan Yoshimitsu'},
	'165': {'165': 'Hakusan', 'full': 'Hakusan Yoshimitsu'},
	'166': {'166': 'Nankaitarou', 'full': 'Nankaitarou Chouson'},
	'167': {'167': 'Nankaitarou', 'full': 'Nankaitarou Chouson'},
	'168': {'168': 'Hizen', 'full': 'Hizen Tadahiro'},
	'169': {'169': 'Hizen', 'full': 'Hizen Tadahiro'},
	'170': {'170': 'Chatannakiri', 'full': 'Chatannakiri'},
	'171': {'171': 'Chatannakiri', 'full': 'Chatannakiri'},
	'172': {'172': 'Kuwana','full': 'Kuwana Gou'},
	'173': {'173': 'Kuwana','full': 'Kuwana Gou'},
	'174': {'174': 'Suishinshi','full': 'Suishinshi Masahide'},
	'175': {'175': 'Suishinshi','full': 'Suishinshi Masahide'},
	'176': {'176': 'Minamoto','full': 'Minamoto Kiyomaro'},
	'177': {'177': 'Minamoto','full': 'Minamoto Kiyomaro'},
	'178': {'178': 'Matsui','full': 'Matsui Gou'},
	'179': {'179': 'Matsui','full': 'Matsui Gou'},
	'180': {'180': 'Sanchoumou','full': 'Sanchoumou'},
	'181': {'181': 'Sanchoumou','full': 'Sanchoumou'},
	'182': {'182': 'Kokindenjunotachi','full': 'Kokindenjunotachi'},
	'183': {'183': 'Kokindenjunotachi','full': 'Kokindenjunotachi'},
	'184': {'184': 'Jizou','full': 'Jizou Yukihira'},
	'185': {'185': 'Jizou','full': 'Yukihira'},
	'186': {'186': 'Chiganemaru','full': 'Chiganemaru'},
	'187': {'187': 'Chiganemaru','full': 'Chiganemaru'},
	'188': {'188': 'Nikkou','full': 'Nikkou Ichimonji'},
	'189': {'189': 'Nikkou','full': 'Nikkou Ichimonji'},
	'190': {'190': 'Taikou','full': 'Taiko Samonji'},
	'191': {'191': 'Taikou','full': 'Taiko Samonji'},
	'192': {'192': 'Samidare','full': 'Samidare Gou'},
	'193': {'193': 'Samidare','full': 'Samidare Gou'},
	'194': {'194': 'Oochidori','full': 'Oochidori Juumonji Yari'},
	'195': {'195': 'Oochidori','full': 'Oochidori Juumonji Yari'},
	'196': {'196': 'Hanjin','full': 'Hanjin'},
	'197': {'197': 'Hanjin','full': 'Hanjin'},
	'198': {'198': 'Norimune','full': 'Ichimonji Norimune'},
	'199': {'199': 'Norimune','full': 'Ichimonji Norimune'},
	'200': {'200': 'Murakumo','full': 'Murakumo Gou'},
	'201': {'201': 'Murakumo','full': 'Murakumo Gou'}
  }
})