define((require, exports, module) => {
  return {
	'1' : 'Omamori',
	'2' : 'Omamori・Kyoku',
	'3' : 'Sennin Dango',
	'4' : 'Fuji Ofuda',
	'5' : 'Pine Ofuda',
	'6' : 'Bamboo Ofuda',
	'7' : 'Plum Ofuda',
	'8' : 'Help Token',
	'9' : 'Kiwame Training Recall Pigeon',
	'10' : 'Swords Room Extension Worker',
	'11' : 'Forge Extension Worker',
	'12' : 'Repairs Extension Worker',
	'13' : 'Koban Box (S)',
	'14' : 'Koban Box (M)',
	'15' : 'Koban Box (L)',
	'16' : 'Armory Extension Worker',
	'17' : 'Makunouchi Bento',
	'18' : 'Letter Set',
	'19' : 'Travel Garb',
	'20' : 'Travel Kit',
	'21' : 'Expedition Recall Pigeon',
	'22' : 'Army Provision',
	'23' : 'Double Box',
	'24' : 'Gramophone',
	'25' : 'Fue',
	'26' : 'Koto',
	'27' : 'Shamisen',
	'28' : 'Taiko',
	'29' : 'Suzu',
	'30' : 'Special Pass',
	'31' : 'Key',
	'32' : 'Treasure Chest Reset Pass',
	'33' : 'Investigation Tools Set',
	'34' : 'Triple Cage',
	'35' : 'Baton',
	'36' : 'Investigation Tools (VoT)',
	'37' : 'One Bite Dango',
	'38' : 'One Bite Dango',
	'39' : 'Umeboshi',
	'40' : 'Umeboshi',
	'41' : 'Investigation Tools Set',
	'42' : 'Treasure Warehouse Key 2',
	'43' : 'Treasure Warehouse Key 3',
	'44' : 'Treasure Warehouse Key 4',
	'45' : 'Transfer Token',
	'46' : 'Transfer Token',
	'47' : 'Osaka Castle Underground Floor Map',
	'48' : 'Gramophone',
	'49' : 'Gramophone',
	'50' : 'Triple Box',
	'51' : 'Triple Box',
	'52' : 'Decuple Box',
	'53' : 'Decuple Box',
	'54' : 'Baton',
	'55' : 'Baton',
	'56' : 'Army Provision',
	'57' : 'Army Provision',
	'58' : 'Exchange Seal',
	'59' : 'Bean Thrower Ofuda',
	'60' : 'Lucky Beans',
	'61' : 'Investigation Tools (VoT)',
	'62' : 'Investigation Tools (VoT)',
	'63' : 'Treasure Chest Reset Pass',
	'64' : 'Triple Cage',
	'65' : 'Triple Cage',
	'66' : 'Decuple Cage',
	'67' : 'Decuple Cage',
	'68' : 'Compost',
	'69' : 'Special Fertilizer',
	'70' : 'Special Fertilizer',
	'71' : 'Tomato',
	'72' : 'Oriental Melon',
	'73' : 'Sunflower',
	'74' : 'Beltfish',
	'75' : 'Exchange Seal',
	'76' : 'Sweet Potatoe',
	'77' : 'Persimmon',
	'78' : 'Chrysanthemum',
	'79' : 'Shishamo',
	'80' : 'Dice',
	'81' : 'Lucky 7 Dice',
	'82' : 'Lucky 7 Dice',
	'83' : 'Shortcut Key',
	'84' : 'Shortcut Key',
	'85' : 'Dried Chestnuts',
	'86' : 'Dried Chestnuts',
	'87' : 'Special Investigation Tools',
	'88' : 'Special Investigation Tools',
	'89' : 'Kouhaku Manjuu',
	'90' : 'Buuterbur Bud',
	'91' : 'Sweet Orange',
	'92' : 'Plum Blossom',
	'93' : 'Clam',
	'94' : 'Sennin Dango',
	'95' : 'Sennin Dango',
	'96' : 'Makunouchi Bento',
	'97' : 'Makunouchi Bento',
	'98' : 'Fiddlehead Fern',
	'99' : 'Cherry',
	'100' : 'Wisteria',
	'101' : 'Sea Urchin',
	'102' : 'Edamame',
	'103' : 'Pear',
	'104' : 'Cosmos',
	'105' : 'Konbu',
	'106' : 'Triple Fish Basket',
	'107' : 'Triple Fish Basket',
	'108' : 'Decuple Fish Basket',
	'109' : 'Decuple Fish Basket',
	'110' : 'Water Artillery Ofuda',
	'111' : 'Water Artillery Ofuda',
	'112' : 'Tailor Ticket',
	'113' : 'Arrowhead',
	'114' : 'Quince',
	'115' : 'Camellia',
	'116' : 'Kichiji Rockfish',
	'117' : 'Oiwaijuu Bento',
	'118' : 'Oiwaijuu Bento',
	'119' : 'Mustard Greens',
	'120' : 'Lemon',
	'121' : 'Rapeseed Flower',
	'122' : 'Japanese Smelt',
	'123' : 'Potato',
	'124' : 'Loquat',
	'125' : 'Lily',
	'126' : 'Turban Shell',
	'127' : 'Pumpkin',
	'128' : 'Fig',
	'129' : 'Gentian',
	'130' : 'Pacific Saury',
	'131' : 'Fuji Ofuda',
	'132' : 'Fuji Ofuda',
	'133' : 'Pine Ofuda',
	'134' : 'Pine Ofuda',
	'135' : 'Bamboo Ofuda',
	'136' : 'Bamboo Ofuda',
	'137' : 'Plum Ofuda',
	'138' : 'Plum Ofuda',
	'139' : 'Bean Thrower Ofuda',
	'140' : 'Bean Thrower Ofuda',
	'141' : 'Kiwame Training Recall Pigeon',
	'142' : 'Kiwame Training Recall Pigeon',
	'143' : 'Scallion',
	'144' : 'European Pear',
	'145' : 'Sasanqua Camellia',
	'146' : 'Ark Clam',
	'147' : 'Investigation Tools (VoTF)',
	'148' : 'Investigation Tools (VoTF)',
	'149' : 'Special Investigation Tools (VoTF)',
	'150' : 'Special Investigation Tools (VoTF)',
	'151' : 'Field Horsetail Shoot',
	'152' : 'Hassaku Orange',
	'153' : 'Japanese Quince',
	'154' : 'Japanese Icefish',
	'155' : 'Broad Bean',
	'156' : 'Plum',
	'157' : 'Japanese Iris',
	'158' : 'Horse Mackerel',
	'1001' : 'White Konpeito'
  }
})